// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.Api.Data;

#nullable disable

namespace ShopOnline.Api.Migrations
{
    [DbContext(typeof(ShopOnlineDbContext))]
    [Migration("20220926003902_correccion_rutas_imagenes")]
    partial class correccion_rutas_imagenes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopOnline.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSencilla/sencilla1.jpg",
                            Name = "Sábanas para cama sencilla 1",
                            Price = 100m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSencilla/sencilla2.jpg",
                            Name = "Sábanas para cama sencilla 2",
                            Price = 50m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSencilla/sencilla3.jpg",
                            Name = "Sábanas para cama sencilla 3",
                            Price = 20m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSencilla/sencilla4.jpg",
                            Name = "Sábanas para cama sencilla 4",
                            Price = 50m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSencilla/sencilla5.jpg",
                            Name = "Sábanas para cama sencilla 5",
                            Price = 30m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble1.jpg",
                            Name = "Sábanas para cama doble 1",
                            Price = 100m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble2.jpg",
                            Name = "Sábanas para cama doble 2",
                            Price = 40m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble3.jpg",
                            Name = "Sábanas para cama doble 3",
                            Price = 40m,
                            Qty = 300
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble4.jpg",
                            Name = "Sábanas para cama doble 4",
                            Price = 600m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble5.jpg",
                            Name = "Sábanas para cama doble 5",
                            Price = 500m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaDoble/doble6.jpg",
                            Name = "Sábanas para cama doble 6",
                            Price = 100m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble1.jpg",
                            Name = "Sábanas para cama semi doble 1",
                            Price = 50m,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble2.jpg",
                            Name = "Sábanas para cama semi doble 2",
                            Price = 50m,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble3.jpg",
                            Name = "Sábanas para cama semi doble 3",
                            Price = 70m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble4.jpg",
                            Name = "Sábanas para cama semi doble 4",
                            Price = 120m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble5.jpg",
                            Name = "Sábanas para cama semi doble 5",
                            Price = 15m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Sábanas género unisex colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/SabanasCamaSemiDoble/semidoble6.jpg",
                            Name = "Sábanas para cama semi doble 6",
                            Price = 20m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo1.png",
                            Name = "Protector colchón cama sencilla 1",
                            Price = 100m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo2.png",
                            Name = "Protector colchón cama sencilla 2",
                            Price = 150m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo3.png",
                            Name = "Protector colchón cama sencilla 3",
                            Price = 200m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo4.png",
                            Name = "Protector colchón cama sencilla 4",
                            Price = 120m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo5.png",
                            Name = "Protector colchón cama sencilla 5",
                            Price = 200m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Protector anti fluidos colchon con dimensiones largo xx, ancho xx, alto xx",
                            ImageURL = "/Images/ProtectorColchonCamaSencilla/protectorsencillo6.png",
                            Name = "Protector colchón cama sencilla 6",
                            Price = 50m,
                            Qty = 150
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sábanas colchón cama sencilla"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sábanas colchón cama semi doble"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sábanas colchón cama doble"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Protectores colchón cama sencilla"
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Miguel"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Lucía"
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.Product", b =>
                {
                    b.HasOne("ShopOnline.Api.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
